# DRONE_HOST=subdomain.example.com
# DRONE_SECRET="$RANDOM$RANDOM$RANDOM"

version: '3.3'

service:

  gogs_git:
    image: gogs/gogs:0.11.66
    ports:
    - '22:22'
    - '80:80'
    volumes:
    - type: volume
      source: gogs_data
      target: /data

  drone_ci:
    image: drone/drone:0.8
    ports:
    - '80:80'
    - '443:443'
    - '9000:9000'
    volumes:
    - drone_ci_data:/var/lib/drone/
    restart: always
    environment:
    - DRONE_OPEN=true
    - DRONE_HOST=${DRONE_HOST}
    - DRONE_ADMIN=rchristian
    - DRONE_GOGS=true
    - DRONE_GOGS_CLIENT=${DRONE_GOGS_CLIENT}
    - DRONE_GOGS_SECRET=${DRONE_GOGS_SECRET}
    - DRONE_SECRET=${DRONE_SECRET}
    - DRONE_LETS_ENCRYPT=true

  drone_agent:
    image: drone/agent:0.8
    command: agent
    restart: always
    depends_on:
    - drone_ci
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - DRONE_SERVER=drone_ci:9000
    - DRONE_SECRET=${DRONE_SECRET}

volumes:
  gogs_data:
    external: false
  drone_ci_data:
    external: false
